import type { MetadataRoute } from "next";

const BASE_URL = "https://www.sharptel.pk";

const staticRoutes = [
  "",
  "/About-us",
  "/Contact-us",
  "/career",
  "/events",
  "/connectivity-solutions",
  "/connectivity-solutions/banking-enterprise",
  "/connectivity-solutions/call-service",
  "/connectivity-solutions/coverage-area",
  "/connectivity-solutions/data-solutions",
  "/connectivity-solutions/enterprise-solutions",
  "/connectivity-solutions/satellite-service",
  "/connectivity-solutions/wireless-connectivity",
  "/manage-technology",
  "/manage-technology/cloud-solutions",
  "/manage-technology/it-bpo-solutions",
  "/manage-technology/manage-it-service",
  "/manage-technology/manage-network-solutions",
  "/manage-technology/manage-security-service",
  "/software-solutions",
  "/software-solutions/crm-erp-solution",
  "/software-solutions/digital-marketing",
  "/software-solutions/graphic-designing",
  "/software-solutions/mobile-app-devlopment",
  "/software-solutions/prototype-devlopment",
  "/software-solutions/webdevlopment",
  "/technology-solutions",
  "/technology-solutions/cyber-security",
  "/technology-solutions/data-center",
  "/technology-solutions/energy-conversation",
  "/technology-solutions/hotspot-wifi",
  "/technology-solutions/iot-automation",
  "/technology-solutions/network-assesment",
  "/technology-solutions/survellience-soluition",
  "/technology-solutions/virtual-solution",
  "/technology-solutions/voice-over",
  "/pages/products",
  "/pages/services",
  "/pages/services/audio-video-conferencing",
  "/pages/services/call-center-solution",
  "/pages/services/data-services",
  "/pages/services/enterprise-internet",
  "/pages/services/internet-data-center",
  "/pages/services/leased-line",
  "/pages/solutions",
  "/pages/solutions/cyber-security",
  "/pages/solutions/data-center",
  "/pages/solutions/wi-fi-hotspot",
  "/pages/solutions/iot-automation",
  "/pages/solutions/voip-solutions",
  "/products/wi-fi-solutions",
  "/products/network-solutions",
  "/products/video-conferencing",
  "/products/audio-solutions",
  "/products/surveillance-systems",
  "/products/voip-solutions",
  "/products/network-security",
  "/products/access-control",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return staticRoutes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : route.split("/").length <= 2 ? 0.8 : 0.6,
  }));
}
